### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by rcwind** [ksvc/KSYLive_Android#10]
java.lang.NullPointerException: Attempt to invoke interface method 'int com.ksy.recordlib.service.core.a.getUploadedKBytes()' on a null object reference

**Comment by FirmianaRain** [comment]
请问是在什么情况下出现的？

**Comment by rcwind** [comment]
关闭activity的时候

**Comment by chriszeng87** [comment]
这个是用的v1.0.2么？

**Comment by rcwind** [comment]
怎么看版本？lib名字没有版本信息啊

**Comment by chriszeng87** [comment]
你帮忙用KSYStreamer.getVersion()方法看一下版本号？

**Comment by rcwind** [comment]
AVFrame.format is not set
08-30 11:41:02.954 991-5375/com.mjmp.startv W/KSYMediaPlayer: AVFrame.width or height is not set

**Comment by rcwind** [comment]
{"sdk_type":"streamer","sdk_ver":30,"sdk_ver_sub":"3.3.0.8","platform":"android","os_ver":"5.1.1","pkg":"xxxxxxxx","dev_model":"SCL-TL00H","dev_id":"868146022998159","log_ver":"1.0.2","log_vn":101}

**Comment by rcwind** [comment]
KSYStreamer.getVersion() Version()=3.3.0.8

**Comment by chriszeng87** [comment]
换最新版吧，这个问题应该已经修复了
