### ISSUE TITLE
How to view streamming

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYLive_Android#11]
Hi,

I have built and run successful KSYLive_Android. When I test in other phone, I add "rtmp://test.uplive.ks-cdn.com/live/androidtest" in NetMediaActivty, but this link cannot play.

Thanks

**Comment by chriszeng87** [comment]
1. Change the url from "rtmp://test.uplive.ks-cdn.com/live/androidtest" to "rtmp://test.uplive.ks-cdn.com/live/ngochuu90" or some other name, the last word is stream name.
2. Play "rtmp://test.rtmplive.ks-cdn.com/live/ngochuu90" in ffplay or any other player. Here is a online player: http://www.cutv.com/demo/live_test.swf

**Comment by ngochuu90** [comment]
Thanks. This completely solves the problem.
