### ISSUE TITLE
书库在使用旧版的openssl所以不允许google商店发布

### ISSUE THREAD

**Issue by huykn** [ksvc/KSYLive_Android#49]
我在使用你们提供的书库，但遇到了几个问题
书库在使用旧版的openssl所以不允许google商店发布
书库在使用openssl 1.0.1o 请更新到 openssl 1.0.2f/1.0.1r 或者 最新的
参考链接 https://support.google.com/faqs/answer/6376725
谢谢

**Comment by fpzeng** [comment]
请问你使用的融合版SDK版本号？

**Comment by huykn** [comment]
我使用的版本，历时：v2.3.3-8801

**Comment by FirmianaRain** [comment]
SDK使用的openssl版本是 1.0.2j
有其他用户使用 SDK提交GooglePlay是没有被拒的
建议看看工程里是否有其他so库使用到了openssl

**Comment by huykn** [comment]
抱歉打扰。我错了。谢谢。
